version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/admin"
    schedule:
      interval: "weekly"
    groups:
      admin-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/mobile/hika_app"
    schedule:
      interval: "weekly"
    groups:
      mobile-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
