// <auto-generated />
using System;
using System.Collections.Generic;
using Hika.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hika.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807145409_BookingsPhase6")]
    partial class BookingsPhase6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hika.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlightingStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("alighting_stop_id");

                    b.Property<Guid>("BoardingStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("boarding_stop_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("PassengerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_user_id");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at_utc");

                    b.Property<int>("SeatsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("seats_requested");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "Hika.Domain.Bookings.Booking.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("total_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_price_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("AlightingStopId")
                        .HasDatabaseName("ix_bookings_alighting_stop_id");

                    b.HasIndex("BoardingStopId")
                        .HasDatabaseName("ix_bookings_boarding_stop_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_bookings_trip_id");

                    b.HasIndex("PassengerUserId", "Status")
                        .HasDatabaseName("ix_bookings_passenger_user_id_status");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Bookings.BookingPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsAccountHolder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_account_holder");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_booking_passengers");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_passengers_booking_id");

                    b.ToTable("booking_passengers", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Bookings.BookingSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("TripSegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_segment_id");

                    b.HasKey("Id")
                        .HasName("pk_booking_segments");

                    b.HasIndex("TripSegmentId")
                        .HasDatabaseName("ix_booking_segments_trip_segment_id");

                    b.HasIndex("BookingId", "TripSegmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_segments_booking_id_trip_segment_id");

                    b.ToTable("booking_segments", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Drivers.DriverProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsVerifiedDriver")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified_driver");

                    b.Property<DateOnly>("LicenseExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("license_expiry_date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("license_number");

                    b.HasKey("Id")
                        .HasName("pk_driver_profiles");

                    b.ToTable("driver_profiles", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Drivers.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_profile_id");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registration_number");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("seat_capacity");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("DriverProfileId")
                        .HasDatabaseName("ix_vehicles_driver_profile_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Drivers.VehiclePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_photos");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_vehicle_photos_vehicle_id");

                    b.ToTable("vehicle_photos", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Trips.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("province");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_locations_name");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("DepartureAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_at_utc");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_profile_id");

                    b.Property<string>("LuggageAllowance")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("luggage_allowance");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalSeatsOffered")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats_offered");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PricePerSeat", "Hika.Domain.Trips.Trip.PricePerSeat#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price_per_seat_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_per_seat_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("DriverProfileId")
                        .HasDatabaseName("ix_trips_driver_profile_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_trips_vehicle_id");

                    b.HasIndex("Status", "DepartureAtUtc")
                        .HasDatabaseName("ix_trips_status_departure_at_utc");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Trips.TripSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FromStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_stop_id");

                    b.Property<int>("SeatsAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("seats_available");

                    b.Property<Guid>("ToStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_stop_id");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PriceOverride", "Hika.Domain.Trips.TripSegment.PriceOverride#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price_override_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_override_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_trip_segments");

                    b.HasIndex("FromStopId")
                        .HasDatabaseName("ix_trip_segments_from_stop_id");

                    b.HasIndex("ToStopId")
                        .HasDatabaseName("ix_trip_segments_to_stop_id");

                    b.HasIndex("TripId", "FromStopId", "ToStopId")
                        .IsUnique()
                        .HasDatabaseName("ix_trip_segments_trip_id_from_stop_id_to_stop_id");

                    b.ToTable("trip_segments", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Trips.TripStop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EstimatedArrivalUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_arrival_utc");

                    b.Property<DateTimeOffset?>("EstimatedDepartureUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_departure_utc");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("province");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("raw_name");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_trip_stops");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_trip_stops_location_id");

                    b.HasIndex("TripId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_trip_stops_trip_id_sequence");

                    b.ToTable("trip_stops", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.TrustSafety.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("document_url");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByAdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_admin_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subject_type");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_verifications");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_verifications_status");

                    b.HasIndex("SubjectType", "SubjectId", "Type")
                        .HasDatabaseName("ix_verifications_subject_type_subject_id_type");

                    b.ToTable("verifications", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Users.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("UserId", "TokenHash")
                        .HasDatabaseName("ix_email_verification_tokens_user_id_token_hash");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Users.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("UserId", "TokenHash")
                        .HasDatabaseName("ix_password_reset_tokens_user_id_token_hash");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Users.PhoneVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_phone_verification_codes");

                    b.HasIndex("UserId", "UsedAtUtc")
                        .HasDatabaseName("ix_phone_verification_codes_user_id_used_at_utc");

                    b.ToTable("phone_verification_codes", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("device_info");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("ix_refresh_tokens_user_id_revoked_at_utc");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<int>("CompletedTripCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_trip_count");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at_utc");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset>("MemberSinceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("member_since_utc");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_verified_at_utc");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("photo_url");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_phone_number")
                        .HasFilter("\"phone_number\" IS NOT NULL");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Hika.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hika.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Hika.Domain.Trips.TripStop", null)
                        .WithMany()
                        .HasForeignKey("AlightingStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_trip_stops_alighting_stop_id");

                    b.HasOne("Hika.Domain.Trips.TripStop", null)
                        .WithMany()
                        .HasForeignKey("BoardingStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_trip_stops_boarding_stop_id");

                    b.HasOne("Hika.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("PassengerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_user_profiles_passenger_user_id");

                    b.HasOne("Hika.Domain.Trips.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_trips_trip_id");
                });

            modelBuilder.Entity("Hika.Domain.Bookings.BookingPassenger", b =>
                {
                    b.HasOne("Hika.Domain.Bookings.Booking", null)
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_passengers_bookings_booking_id");
                });

            modelBuilder.Entity("Hika.Domain.Bookings.BookingSegment", b =>
                {
                    b.HasOne("Hika.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_segments_bookings_booking_id");

                    b.HasOne("Hika.Domain.Trips.TripSegment", null)
                        .WithMany()
                        .HasForeignKey("TripSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_segments_trip_segments_trip_segment_id");
                });

            modelBuilder.Entity("Hika.Domain.Drivers.DriverProfile", b =>
                {
                    b.HasOne("Hika.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Hika.Domain.Drivers.DriverProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_profiles_asp_net_users_id");
                });

            modelBuilder.Entity("Hika.Domain.Drivers.Vehicle", b =>
                {
                    b.HasOne("Hika.Domain.Drivers.DriverProfile", null)
                        .WithMany()
                        .HasForeignKey("DriverProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_driver_profiles_driver_profile_id");
                });

            modelBuilder.Entity("Hika.Domain.Drivers.VehiclePhoto", b =>
                {
                    b.HasOne("Hika.Domain.Drivers.Vehicle", null)
                        .WithMany("Photos")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_photos_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Hika.Domain.Trips.Trip", b =>
                {
                    b.HasOne("Hika.Domain.Drivers.DriverProfile", null)
                        .WithMany()
                        .HasForeignKey("DriverProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_driver_profiles_driver_profile_id");

                    b.HasOne("Hika.Domain.Drivers.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Hika.Domain.Trips.TripSegment", b =>
                {
                    b.HasOne("Hika.Domain.Trips.TripStop", null)
                        .WithMany()
                        .HasForeignKey("FromStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_segments_trip_stops_from_stop_id");

                    b.HasOne("Hika.Domain.Trips.TripStop", null)
                        .WithMany()
                        .HasForeignKey("ToStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_segments_trip_stops_to_stop_id");

                    b.HasOne("Hika.Domain.Trips.Trip", null)
                        .WithMany("Segments")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_segments_trips_trip_id");
                });

            modelBuilder.Entity("Hika.Domain.Trips.TripStop", b =>
                {
                    b.HasOne("Hika.Domain.Trips.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trip_stops_locations_location_id");

                    b.HasOne("Hika.Domain.Trips.Trip", null)
                        .WithMany("Stops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_stops_trips_trip_id");
                });

            modelBuilder.Entity("Hika.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("Hika.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Hika.Domain.Users.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_asp_net_users_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Hika.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Hika.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Hika.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Hika.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Hika.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("Hika.Domain.Drivers.Vehicle", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Hika.Domain.Trips.Trip", b =>
                {
                    b.Navigation("Segments");

                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
