using FirebaseAdmin.Messaging;
using Hika.Application.Notifications.Ports;
using Microsoft.Extensions.Logging;
using FirebaseApp = FirebaseAdmin.FirebaseApp;
using FirebaseNotification = FirebaseAdmin.Messaging.Notification;

namespace Hika.Infrastructure.Notifications;

/// <summary>
/// Real FCM delivery via the Firebase Admin SDK. Only registered when
/// Firebase:ServiceAccountJson is configured (see DependencyInjection.AddInfrastructure) — going
/// live additionally requires the mobile app to carry a real firebase_options.dart (generated by
/// `flutterfire configure` against the same Firebase project the service account belongs to),
/// which only the project owner can produce since it needs a Firebase account/console session.
/// </summary>
public sealed class FirebasePushSender(FirebaseApp firebaseApp, ILogger<FirebasePushSender> logger) : IPushSender
{
    public async Task SendAsync(
        IReadOnlyCollection<string> deviceTokens, string title, string body, IReadOnlyDictionary<string, string>? data, CancellationToken cancellationToken)
    {
        var message = new MulticastMessage
        {
            // Tokens (not the newer Fids) is deliberate — Fids addresses Firebase Installation
            // IDs, a different identifier space than the FCM registration tokens this app
            // collects via DeviceTokenService. SDK marks Tokens obsolete but it remains functional.
            Tokens = deviceTokens.ToList(),
            Notification = new FirebaseNotification { Title = title, Body = body },
            Data = data,
        };

        var messaging = FirebaseMessaging.GetMessaging(firebaseApp);
        var response = await messaging.SendEachForMulticastAsync(message, cancellationToken);

        if (response.FailureCount > 0)
        {
            logger.LogWarning(
                "Push delivery failed for {FailureCount}/{TotalCount} device(s)", response.FailureCount, deviceTokens.Count);
        }
    }
}
